project:
  type: website

website:
  title: "Final Project Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Outcome"
        href: outcome.qmd
      - text: "Case Study"
        href: casestudy.qmd
      - text: "Policy Implication"
        href: policyimplication.qmd

