---
title: "Introduction"
editor: 
  markdown: 
    wrap: 72
---

## Data

This study aims to collect data from media outlets in major economies
such as the United States, the United Kingdom, Canada, China, and Japan
to facilitate a comprehensive comparison of communication styles
regarding US monetary policy. However, due to limited access to some
media outlets' APIs, the study will focus on data from sources that
offer free API subscriptions. At present, the available media outlets
include The New York Times from the United States and The Guardian from
the United Kingdom. While these sources provide valuable observations,
they only represent two countries. Therefore, the next step of this
study will be to explore additional media sources to gain more diverse
insights into communication styles.

The current dataset consists of 1,000 observations, with 500 from The
New York Times and 500 from The Guardian. The dataset includes the
following features: headline, snippet, website url, and publication
date. The visualizations below provide an overview of the "snippet"
column for The Guardian data. Some key words like "inflation", "interest
rate" and "central ban" are frequently mentioned, which is consistent
with searching plan. However, additional steps are required before
applying data science methodologies, such as refining search filters to
capture accurate mentions of US interest rates, capturing words
representing emotions, expanding the stop words list to exclude
irrelevant content, removing verb tenses, normalizing the data, and
more.

## Methodology

To compare communication styles across media outlets from different
countries, this study will employ the following data science
methodologies:

-   Dimensionality Reduction (PCA): Principal Component Analysis will be
    applied to reduce the complexity of the text data, focusing on key
    features from media outlets in various countries. This technique
    allows for comparisons based on a smaller subset of features that
    capture the greatest variance in communication styles. One example
    of PCA application that could serve as a reference involves
    researchers collecting text data from political debates and
    speeches. They extracted key linguistic features, such as sentiment,
    keyword frequency, and tone, and applied PCA to reduce the number of
    variables. This enabled them to identify underlying dimensions and
    map out how different political parties' communication styles
    varied.

-   Clustering Analysis: After reducing the dimensionality of the
    dataset, clustering techniques such as k-means or hierarchical
    clustering will be used to group media outlets based on the
    similarities in their communication styles. This approach will help
    identify which countries or regions tend to adopt similar narrative
    patterns when discussing US interest rates, potentially reflecting
    geopolitical or economic alignment.
